{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [],
   "source": [
    "Today = '2024-04-30'\n",
    "Mounth = 'Apr'\n",
    "\n",
    "Print_ARAP = True\n",
    "print_manual_map = True\n",
    "\n",
    "import os\n",
    "from datetime import date\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "\n",
    "import sys\n",
    "sys.path.append(\"C:\\\\Users\\\\KlimovaAnnaA\\\\Documents\\\\MyFiles\\\\Projects\\\\OCP\")\n",
    "from Defs import merge_SalesUnits\n",
    "from Defs import merge_Mapping\n",
    "from Defs import Period\n",
    "from Defs import new_list\n",
    "from Defs import export_from_RISKCUSTOM\n",
    "from Defs import add_in_currency_column\n",
    "from Defs import concat_columns\n",
    "from Defs import export_from_WHWEEK"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\KlimovaAnnaA\\Documents\\MyFiles\\Projects\\OCP\\Defs.py:168: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  data_export = pd.read_sql(query, con=connection)\n",
      "C:\\Users\\KlimovaAnnaA\\AppData\\Local\\Temp\\ipykernel_9916\\1349408809.py:17: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  data_work_externalReceivableDebt['Cty_code'] = merge_Mapping(data_work_externalReceivableDebt, 'customerName')\n",
      "C:\\Users\\KlimovaAnnaA\\Documents\\MyFiles\\Projects\\OCP\\Defs.py:89: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  data_export = pd.read_sql(query, con=connection)\n",
      "C:\\Users\\KlimovaAnnaA\\Documents\\MyFiles\\Projects\\OCP\\Defs.py:34: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['SAMSALES' 'SAMSALES' 'SAMSALES' ... 'SAMSALES' 'SAMSALES' 'SAMSALES']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.\n",
      "  merge_data.loc[merge_data[f'{id_col}_merge'] != 'External', 'last_merge'] = merge_data.loc[merge_data[f'{id_col}_merge'] != 'External', f'{id_col}_merge']\n",
      "C:\\Users\\KlimovaAnnaA\\AppData\\Local\\Temp\\ipykernel_9916\\1349408809.py:18: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  data_work_externalReceivableDebt['Cty_segment'] = merge_SalesUnits(data_work_externalReceivableDebt, 'Cty_code', merge_col='ocpSegment')\n",
      "C:\\Users\\KlimovaAnnaA\\Documents\\MyFiles\\Projects\\OCP\\Defs.py:89: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  data_export = pd.read_sql(query, con=connection)\n",
      "C:\\Users\\KlimovaAnnaA\\Documents\\MyFiles\\Projects\\OCP\\Defs.py:34: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['SAMSALES' 'SAMSALES' 'SAMSALES' ... 'SAMSALES' 'SAMSALES' 'SAMSALES']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.\n",
      "  merge_data.loc[merge_data[f'{id_col}_merge'] != 'External', 'last_merge'] = merge_data.loc[merge_data[f'{id_col}_merge'] != 'External', f'{id_col}_merge']\n",
      "C:\\Users\\KlimovaAnnaA\\AppData\\Local\\Temp\\ipykernel_9916\\1349408809.py:19: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  data_work_externalReceivableDebt['Comp_segment'] = merge_SalesUnits(data_work_externalReceivableDebt, 'companyCode', merge_col='ocpSegment')\n",
      "C:\\Users\\KlimovaAnnaA\\Documents\\MyFiles\\Projects\\OCP\\Defs.py:89: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  data_export = pd.read_sql(query, con=connection)\n",
      "C:\\Users\\KlimovaAnnaA\\Documents\\MyFiles\\Projects\\OCP\\Defs.py:34: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['EUROCHEM' 'EUROCHEM' 'EUROCHEM' ... 'EUROCHEM' 'EUROCHEM' 'EUROCHEM']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.\n",
      "  merge_data.loc[merge_data[f'{id_col}_merge'] != 'External', 'last_merge'] = merge_data.loc[merge_data[f'{id_col}_merge'] != 'External', f'{id_col}_merge']\n",
      "C:\\Users\\KlimovaAnnaA\\AppData\\Local\\Temp\\ipykernel_9916\\1349408809.py:20: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  data_work_externalReceivableDebt['Comp_holding'] = merge_SalesUnits(data_work_externalReceivableDebt, 'companyCode', merge_col='holding')\n",
      "C:\\Users\\KlimovaAnnaA\\Documents\\MyFiles\\Projects\\OCP\\Defs.py:101: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['CCY_to'] = CCY_to\n",
      "C:\\Users\\KlimovaAnnaA\\Documents\\MyFiles\\Projects\\OCP\\Defs.py:105: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = DATE\n",
      "C:\\Users\\KlimovaAnnaA\\Documents\\MyFiles\\Projects\\OCP\\Defs.py:95: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['concat_columns'] = df[columns].astype(str).apply(lambda row: '_'.join(row.values.astype(str)), axis=1)\n",
      "C:\\Users\\KlimovaAnnaA\\Documents\\MyFiles\\Projects\\OCP\\Defs.py:89: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  data_export = pd.read_sql(query, con=connection)\n",
      "C:\\Users\\KlimovaAnnaA\\Documents\\MyFiles\\Projects\\OCP\\Defs.py:156: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`\n",
      "  df[f'Coef_to_{CCY_to}'] = df.date_CCY_from.replace(coef_dict).fillna(0)\n",
      "C:\\Users\\KlimovaAnnaA\\Documents\\MyFiles\\Projects\\OCP\\Defs.py:168: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  data_export = pd.read_sql(query, con=connection)\n",
      "C:\\Users\\KlimovaAnnaA\\AppData\\Local\\Temp\\ipykernel_9916\\1349408809.py:42: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  data_work_externalPayableDebt['Cty_code'] = merge_Mapping(data_work_externalPayableDebt, 'vendorName')\n",
      "C:\\Users\\KlimovaAnnaA\\Documents\\MyFiles\\Projects\\OCP\\Defs.py:89: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  data_export = pd.read_sql(query, con=connection)\n",
      "C:\\Users\\KlimovaAnnaA\\Documents\\MyFiles\\Projects\\OCP\\Defs.py:34: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['SAMSALES' 'SAMSALES' 'SAMSALES' ... 'SAMSALES' 'TRADING' 'SAMSALES']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.\n",
      "  merge_data.loc[merge_data[f'{id_col}_merge'] != 'External', 'last_merge'] = merge_data.loc[merge_data[f'{id_col}_merge'] != 'External', f'{id_col}_merge']\n",
      "C:\\Users\\KlimovaAnnaA\\AppData\\Local\\Temp\\ipykernel_9916\\1349408809.py:43: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  data_work_externalPayableDebt['Cty_segment'] = merge_SalesUnits(data_work_externalPayableDebt, 'Cty_code', merge_col='ocpSegment')\n",
      "C:\\Users\\KlimovaAnnaA\\Documents\\MyFiles\\Projects\\OCP\\Defs.py:89: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  data_export = pd.read_sql(query, con=connection)\n",
      "C:\\Users\\KlimovaAnnaA\\Documents\\MyFiles\\Projects\\OCP\\Defs.py:34: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['SAMSALES' 'SAMSALES' 'SAMSALES' ... 'SAMSALES' 'SAMSALES' 'SAMSALES']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.\n",
      "  merge_data.loc[merge_data[f'{id_col}_merge'] != 'External', 'last_merge'] = merge_data.loc[merge_data[f'{id_col}_merge'] != 'External', f'{id_col}_merge']\n",
      "C:\\Users\\KlimovaAnnaA\\AppData\\Local\\Temp\\ipykernel_9916\\1349408809.py:44: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  data_work_externalPayableDebt['Comp_segment'] = merge_SalesUnits(data_work_externalPayableDebt, 'companyCode', merge_col='ocpSegment')\n",
      "C:\\Users\\KlimovaAnnaA\\Documents\\MyFiles\\Projects\\OCP\\Defs.py:89: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  data_export = pd.read_sql(query, con=connection)\n",
      "C:\\Users\\KlimovaAnnaA\\Documents\\MyFiles\\Projects\\OCP\\Defs.py:34: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['EUROCHEM' 'EUROCHEM' 'EUROCHEM' ... 'EUROCHEM' 'EUROCHEM' 'EUROCHEM']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.\n",
      "  merge_data.loc[merge_data[f'{id_col}_merge'] != 'External', 'last_merge'] = merge_data.loc[merge_data[f'{id_col}_merge'] != 'External', f'{id_col}_merge']\n",
      "C:\\Users\\KlimovaAnnaA\\AppData\\Local\\Temp\\ipykernel_9916\\1349408809.py:45: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  data_work_externalPayableDebt['Comp_holding'] = merge_SalesUnits(data_work_externalPayableDebt, 'companyCode', merge_col='holding')\n",
      "C:\\Users\\KlimovaAnnaA\\Documents\\MyFiles\\Projects\\OCP\\Defs.py:101: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['CCY_to'] = CCY_to\n",
      "C:\\Users\\KlimovaAnnaA\\Documents\\MyFiles\\Projects\\OCP\\Defs.py:105: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['date'] = DATE\n",
      "C:\\Users\\KlimovaAnnaA\\Documents\\MyFiles\\Projects\\OCP\\Defs.py:95: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['concat_columns'] = df[columns].astype(str).apply(lambda row: '_'.join(row.values.astype(str)), axis=1)\n",
      "C:\\Users\\KlimovaAnnaA\\Documents\\MyFiles\\Projects\\OCP\\Defs.py:89: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  data_export = pd.read_sql(query, con=connection)\n",
      "C:\\Users\\KlimovaAnnaA\\Documents\\MyFiles\\Projects\\OCP\\Defs.py:156: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`\n",
      "  df[f'Coef_to_{CCY_to}'] = df.date_CCY_from.replace(coef_dict).fillna(0)\n"
     ]
    }
   ],
   "source": [
    "# query = \"\"\"\n",
    "# SELECT * \n",
    "# FROM \"XXWH\".\"externalReceivableDebt\"\n",
    "# ORDER BY \"reportDate\" DESC\n",
    "# FETCH FIRST 10 ROWS ONLY\n",
    "# \"\"\"\n",
    "query = f\"\"\"\n",
    "SELECT * \n",
    "FROM \"XXWH\".\"externalReceivableDebt\"\n",
    "WHERE \"reportDate\" = TO_DATE('{Today}', 'YYYY-MM-DD') \n",
    "\"\"\"\n",
    "\n",
    "# invoiceDate\n",
    "data = export_from_WHWEEK(query)\n",
    "data_work_externalReceivableDebt = data[['companyCode', 'customerName', 'outGroupUS', 'currencyCode', 'amount', 'termDate']]\n",
    "# Merge\n",
    "data_work_externalReceivableDebt['Cty_code'] = merge_Mapping(data_work_externalReceivableDebt, 'customerName')\n",
    "data_work_externalReceivableDebt['Cty_segment'] = merge_SalesUnits(data_work_externalReceivableDebt, 'Cty_code', merge_col='ocpSegment')\n",
    "data_work_externalReceivableDebt['Comp_segment'] = merge_SalesUnits(data_work_externalReceivableDebt, 'companyCode', merge_col='ocpSegment')\n",
    "data_work_externalReceivableDebt['Comp_holding'] = merge_SalesUnits(data_work_externalReceivableDebt, 'companyCode', merge_col='holding')\n",
    "# Currency\n",
    "data_work_externalReceivableDebt = add_in_currency_column(data_work_externalReceivableDebt, 'USD', 'currencyCode', False, 'amount', Today)\n",
    "# Period\n",
    "data_work_externalReceivableDebt = Period(data_work_externalReceivableDebt, Today, 'termDate')\n",
    "# Pivot\n",
    "data_pivot = data_work_externalReceivableDebt.pivot_table(index=['Comp_holding', 'companyCode', 'Comp_segment', 'outGroupUS'], values='amount_in_USD', aggfunc={'amount_in_USD':['sum','count']}).reset_index()\n",
    "# to excel\n",
    "if Print_ARAP == True:\n",
    "    Output_file = f'{str(date.today())}_externalReceivableDebt_pivot_{Mounth}.xlsx'\n",
    "    data_pivot.to_excel(Output_file, sheet_name='Pivot', index=False)\n",
    "    new_list(data_work_externalReceivableDebt, Output_file, 'export_data')\n",
    "\n",
    "query = f\"\"\"\n",
    "SELECT * \n",
    "FROM \"XXWH\".\"externalPayableDebt\"\n",
    "WHERE \"reportDate\" = TO_DATE('{Today}', 'YYYY-MM-DD') \n",
    "\"\"\"\n",
    "# invoiceDate\n",
    "data = export_from_WHWEEK(query)\n",
    "data_work_externalPayableDebt = data[['companyCode', 'vendorName', 'outGroupUS', 'currencyCode', 'amount', 'termDate']]\n",
    "# Merge\n",
    "data_work_externalPayableDebt['Cty_code'] = merge_Mapping(data_work_externalPayableDebt, 'vendorName')\n",
    "data_work_externalPayableDebt['Cty_segment'] = merge_SalesUnits(data_work_externalPayableDebt, 'Cty_code', merge_col='ocpSegment')\n",
    "data_work_externalPayableDebt['Comp_segment'] = merge_SalesUnits(data_work_externalPayableDebt, 'companyCode', merge_col='ocpSegment')\n",
    "data_work_externalPayableDebt['Comp_holding'] = merge_SalesUnits(data_work_externalPayableDebt, 'companyCode', merge_col='holding')\n",
    "# Currency\n",
    "data_work_externalPayableDebt = add_in_currency_column(data_work_externalPayableDebt, 'USD', 'currencyCode', False, 'amount', Today)\n",
    "# Period\n",
    "data_work_externalPayableDebt = Period(data_work_externalPayableDebt, Today, 'termDate')\n",
    "# Pivot\n",
    "data_pivot = data_work_externalPayableDebt.pivot_table(index=['Comp_holding', 'companyCode', 'Comp_segment', 'outGroupUS'], values='amount_in_USD', aggfunc={'amount_in_USD':['sum','count']}).reset_index()\n",
    "# to excel\n",
    "if Print_ARAP == True:\n",
    "    Output_file = f'{str(date.today())}_externalPayableDebt_pivot_{Mounth}.xlsx'\n",
    "    data_pivot.to_excel(Output_file, sheet_name='pivot', index=False)\n",
    "    new_list(data_work_externalPayableDebt, Output_file, 'export_data')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1 is empty\n"
     ]
    }
   ],
   "source": [
    "count = 0\n",
    "for data_check in [data_work_externalReceivableDebt, data_work_externalPayableDebt]:\n",
    "    count = count + 1\n",
    "    if count == 1:\n",
    "        cty_col = 'customerName'\n",
    "    else:\n",
    "        cty_col = 'vendorName'\n",
    "    check_data = data_check.loc[(data_check['outGroupUS'] == 'Internal') & (data_check['Cty_segment'] == 'External'),\\\n",
    "                                                        [cty_col, 'Cty_code', 'Cty_segment']].drop_duplicates()\n",
    "    check_data2 = data_check.loc[(data_check['outGroupUS'] == 'Internal') & (data_check['Comp_segment'] == 'External'),\\\n",
    "                                                        ['companyCode', 'Comp_segment']].drop_duplicates()\n",
    "    check = pd.concat([check_data2, check_data])\n",
    "    if len(check) != 0:\n",
    "        if print_manual_map == True:\n",
    "            check.to_excel(f'manual_map_Braz_{count}.xlsx', index=False)\n",
    "    else:\n",
    "       print(f'{count} is empty') "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
